
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                yy_size_t yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 94
#define YY_END_OF_BUFFER 95
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[435] =
    {   0,
        0,    0,   95,   93,    1,    1,   93,   93,   93,   74,
       93,   93,   90,   72,   70,   90,   71,   73,   77,   90,
       93,   56,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   93,    1,   64,    0,   92,    0,    0,   75,   62,
        0,   57,    0,   66,   63,   68,   80,   67,   58,   60,
        0,   77,    0,   90,   59,   61,   89,   89,   89,   89,
       89,   11,   89,   19,   20,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   37,   89,   89,   89,   89,
       89,   89,   48,   89,   89,   89,   89,   89,   69,    0,

       92,    0,    0,    0,    0,    0,    0,    0,   76,    0,
        0,    0,    0,    0,    0,   65,   80,    0,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   27,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   46,   89,   89,   89,   89,   89,   89,   89,
       89,    0,   91,   78,    0,    0,    0,    0,   76,   85,
       86,    0,    0,    0,    0,    0,    0,    0,    0,   89,
        3,   89,   89,   89,    7,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,

       89,   89,   89,   89,   31,   89,   89,   89,   36,   38,
       39,   89,   89,   89,   89,   89,   45,   89,   49,   89,
       89,   89,   89,   89,   89,    0,   78,    0,   79,    0,
        0,   87,    0,   88,    0,    0,   81,   89,   89,   89,
        6,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   28,   89,   89,   32,
       89,   34,   89,   89,   89,   89,   89,   89,   89,   51,
       89,   52,   89,   54,   89,    0,    0,    0,   79,    0,
       89,    4,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   17,   89,   21,   89,   89,   89,   89,   89,   89,

       89,   89,   89,   89,   89,   89,   89,   89,   47,   50,
       53,   89,    0,   82,   79,    0,    0,   89,   89,   89,
       89,   89,   12,   89,   89,   15,   89,   89,   89,   89,
       89,   89,   26,   29,   89,   89,   89,   89,   41,   89,
       89,   44,   89,    0,    0,   89,    5,   89,   89,   89,
       89,   14,   16,   89,   89,   89,   24,   89,   30,   33,
       35,   89,   42,   89,   89,    0,   83,    2,   89,   89,
       10,   89,   89,   89,   89,   25,   40,   43,   55,    0,
        8,   89,   13,   89,   22,   23,    0,    9,   18,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   84,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   16,   29,
       30,   31,    1,    1,   32,   33,   34,   35,   36,   37,
       38,   39,   40,   41,   42,   43,   44,   45,   46,   47,
       48,   49,   50,   51,   52,   53,   42,   54,   42,   55,
       56,   57,   58,   59,   42,    1,   60,   61,   62,   63,

       64,   65,   66,   67,   68,   69,   42,   70,   71,   72,
       73,   74,   75,   76,   77,   78,   79,   80,   42,   81,
       42,   82,   83,   84,   85,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[86] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    1,
        1,    1,    1,    4,    1,    1,    1,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    1,    1,    1,
        1,    5,    5,    5,    5,    5,    5,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    1,    1,    1,    1,    5,
        5,    5,    5,    5,    5,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    7,    1,    7
    } ;

static const flex_int16_t yy_base[444] =
    {   0,
        0,    0,  838, 1040,   84,   86,  804,  823,   84,   77,
      802,  823, 1040,   80,  799,   99,   63,  798,  113,  799,
      774,   73,   80,    0,  110,   79,  104,  107,   93,  114,
      107,  128,  121,  130,  115,  147,  133,  152,  162,  155,
      155,  756,  103, 1040,  722,    0,  105,  764,  214, 1040,
      754, 1040,  274,  706, 1040, 1040,  222, 1040, 1040, 1040,
      232,  246,  654, 1040, 1040, 1040,    0,  118,  226,  169,
      232,  268,  167,  257,  279,  222,  250,  272,  235,  242,
      277,  241,  271,  287,  293,    0,  273,  282,  292,  307,
      327,  299,  316,  329,  319,  316,  323,  321, 1040,  675,

        0,  106,  202,  647,  356,  724,  648,  721,  149,  718,
      386,  405,  424,  397,    0, 1040,  434,  652,  320,  402,
      403,  322,  391,  390,  429,  418,  424,  437,  440,  437,
      431,  444,  441,  430,  432,  445,  443,  451,  450,  449,
      450,  448,  443,  435,  446,  460,  462,  463,  474,  470,
      460,  481,    0,  474,  480,  485,  497,  485,  492,  488,
      495,  662, 1040,  519,  546,  641,    0,  704,  519, 1040,
     1040,  566,  585,  604,  681,  610,  627,  668,  640,  496,
        0,  502,  515,  514,    0,  563,  533,  581,  568,  599,
      602,  612,  608,  604,  623,  637,  621,  622,  628,  640,

      635,  639,  633,  636,    0,  637,  648,  636,    0,    0,
        0,  654,  657,  642,  656,  653,    0,  662,    0,  663,
      653,  653,  662,  665,  664,  667,  720,  203,    0,    0,
      565, 1040,  629, 1040,  628,  728,  738,  734,  735,  718,
        0,  738,  727,  722,  722,  722,  725,  744,  733,  731,
      745,  742,  749,  749,  754,  741,    0,  745,  752,    0,
      746,    0,  755,  753,  773,  780,  777,  785,  773,    0,
      777,    0,  793,    0,  793,  563,  837,  613,  554,  204,
      801,    0,  801,  794,  789,  790,  798,  811,  810,  816,
      811,    0,  820,    0,  827,  816,  819,  832,  829,  832,

      844,  849,  850,  837,  839,  842,  847,  843,    0,    0,
        0,  847,  532,  900,   84,  859,  595,  850,  854,  854,
      865,  875,    0,  863,  880,    0,  885,  874,  893,  885,
      902,  892,    0,    0,  893,  891,  892,  903,    0,  912,
      910,    0,  910,  542,    0,  902,    0,  913,  900,  903,
      907,    0,    0,  914,  921,  908,    0,  914,    0,    0,
        0,  914,    0,  917,  918,  542,    0,    0,  920,  930,
        0,  932,  939,  942,  957,    0,    0,    0,    0,  590,
        0,  942,    0,  947,    0,    0,  591,    0,    0,  530,
      510,  505,  502,  521,  492,  505,  552,  500,  470,  463,

      449,  381,  353,  384,  388,  380,  311,  305,  329,  378,
      328,  316,  343,  279,  273,  307,  309,  293,  226,  270,
      217,  242,  248,  187,  163,  131,  190,  192,  184,   87,
      160,  147, 1040, 1040, 1015, 1021, 1028, 1031,  145,  125,
     1034,  123,  109
    } ;

static const flex_int16_t yy_def[444] =
    {   0,
      434,    1,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  434,  434,  434,  434,  436,  437,  434,  434,  434,
      438,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  434,  434,

      436,  437,  437,  434,  434,  434,  434,  434,  438,  434,
      434,  434,  434,  434,  439,  434,  434,  434,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  434,  434,  434,  434,  434,  440,  434,  438,  434,
      434,  434,  434,  434,  434,  434,  434,  441,  434,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,

      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  434,  434,  434,  440,  442,
      434,  434,  434,  434,  434,  434,  434,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  434,  434,  434,  442,  434,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,

      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  434,  434,  442,  434,  434,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  434,  443,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  434,  443,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  434,
      435,  435,  435,  435,  435,  435,  434,  435,  435,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,

      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,    0,  434,  434,  434,  434,  434,  434,
      434,  434,  434
    } ;

static const flex_int16_t yy_nxt[1126] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       13,   14,   15,   16,   17,   13,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
        4,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       24,   24,   32,   33,   34,   35,   36,   24,   37,   38,
       39,   40,   41,   24,   24,    4,    4,    4,   42,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   24,   32,
       33,   34,   35,   36,   24,   37,   38,   39,   40,   41,
       24,   24,   13,   13,   13,   43,   43,   43,   43,   46,
       48,   54,   58,   59,   49,   49,   49,   49,   49,   49,

       49,   49,   66,   64,   43,   43,   50,  103,  103,   55,
      104,  104,   68,  367,   72,   51,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   61,  279,   80,  229,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       68,   69,   72,   51,   73,   81,   78,  315,   74,  178,
       82,  433,   70,   75,   76,   71,   80,   77,   79,   83,
       84,   85,  168,   86,  231,   87,   47,  119,   91,   69,
      432,  431,   73,   81,   78,   74,   63,   82,   88,   70,
       75,   76,   71,   92,   77,   79,   98,   83,   84,   85,
       86,   93,   87,   94,  119,   89,   91,   96,   90,   97,

      122,   95,  128,  430,  103,  429,   88,  104,  428,  277,
      316,   92,  169,  427,   98,  278,  317,  278,  317,   93,
      426,   94,   89,  425,   96,   90,   97,  106,  122,   95,
      128,   49,   49,   49,   49,   49,   49,   49,   49,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,  117,
      117,  117,  117,  117,  117,  117,  117,  117,  117,   61,
      120,  135,  424,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,  423,  121,  123,  124,  107,  110,  139,
      110,  422,  110,  136,  421,  420,  140,  143,  120,  135,
      129,  111,  111,  112,  113,  113,  113,  113,  113,  113,

      113,  121,  123,  124,  125,  137,  139,  130,  131,   63,
      141,  136,  132,  140,  143,  144,  138,  126,  129,  419,
      127,  147,  145,  418,  417,  133,  142,  146,  416,  134,
      148,  149,  125,  137,  130,  131,  415,  150,  141,  151,
      132,  154,  144,  138,  126,  110,  114,  127,  147,  110,
      145,  110,  133,  142,  115,  146,  134,  148,  152,  149,
      155,  156,  160,  153,  150,  158,  159,  151,  154,  161,
      180,  184,  157,  164,  164,  164,  164,  164,  164,  164,
      164,  414,  413,  412,  411,  410,  152,  155,  409,  156,
      160,  153,  158,  159,  171,  408,  161,  180,  184,  157,

      407,  406,  405,  172,  172,  172,  172,  172,  172,  172,
      172,  172,  172,  171,  176,  176,  176,  176,  177,  177,
      177,  177,  173,  173,  173,  173,  173,  174,  175,  175,
      175,  175,  171,  181,  183,  404,  185,  182,  403,  186,
      187,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  117,  117,  117,  117,  117,  117,  117,  117,  117,
      117,  181,  183,  185,  188,  182,  186,  187,  189,  190,
      191,  192,  193,  402,  194,  195,  196,  401,  197,  198,
      199,  200,  201,  202,  203,  204,  205,  400,  206,  207,
      208,  209,  188,  210,  211,  189,  190,   63,  191,  192,

      193,  194,  216,  195,  196,  197,  198,  214,  199,  200,
      201,  202,  203,  204,  205,  206,  207,  208,  212,  209,
      215,  210,  211,  217,  218,  219,  213,  220,  221,  216,
      222,  223,  168,  224,  225,  214,  164,  164,  164,  164,
      164,  164,  164,  164,  238,  212,  239,  215,  240,  241,
      217,  218,  219,  213,  220,  399,  221,  222,  398,  223,
      224,  397,  225,  227,  227,  227,  227,  227,  227,  227,
      227,  238,  243,  239,  171,  396,  240,  241,  395,  394,
      393,  392,  169,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  171,  391,  390,  387,  380,  366,  231,

      243,  316,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  171,  242,  244,  344,  245,  315,  232,  277,
      313,  175,  175,  175,  175,  175,  175,  177,  177,  177,
      177,  177,  177,  177,  177,  232,  234,  232,  280,  250,
      242,  246,  244,  245,  233,  233,  233,  233,  233,  233,
      233,  233,  236,  247,  236,  248,  249,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  250,  246,  251,
      252,  276,  253,  254,  255,  256,  234,  257,  258,  262,
      247,  259,  248,  249,  260,  261,  263,  264,  265,  171,
      266,  267,  268,  269,  270,  275,  251,  271,  252,  253,

      254,  255,  272,  256,  257,  273,  258,  262,  259,  274,
      230,  260,  261,  263,  228,  264,  265,  266,  226,  267,
      268,  269,  270,  275,  271,  179,  170,  167,  166,  272,
      165,  163,  273,  162,  118,  116,  274,  227,  227,  227,
      227,  227,  227,  227,  227,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  281,  282,  108,  283,  284,
      105,  286,  287,  288,  289,  290,  291,  100,  292,  293,
      294,  295,  296,  107,  297,   99,  285,  298,   65,  299,
      300,  301,  304,  281,  282,  283,  302,  284,  286,  287,

      288,  289,  290,  303,  291,  292,  293,  305,  294,  295,
      296,  306,  297,  285,  307,  298,  299,  300,  308,  301,
      304,  309,  310,  302,  311,  312,   64,   60,   56,   53,
      303,   52,   45,   44,  318,  305,  319,  434,  320,  306,
      321,  322,  307,  323,  324,  325,  308,  326,  309,  310,
      327,  328,  311,  312,  314,  314,  314,  314,  314,  314,
      314,  314,  318,  329,  319,  320,  330,  321,  322,  331,
      323,  332,  324,  325,  333,  326,  334,  335,  327,  328,
      336,  337,  434,  338,  339,  340,  341,  434,  342,  343,
      434,  329,  434,  330,  434,  434,  331,  345,  349,  332,

      346,  333,  347,  334,  348,  335,  350,  354,  336,  337,
      338,  339,  340,  351,  341,  342,  343,  314,  314,  314,
      314,  314,  314,  314,  314,  345,  349,  346,  352,  347,
      353,  348,  355,  357,  350,  354,  356,  358,  359,  360,
      351,  361,  362,  363,  364,  365,  434,  368,  369,  434,
      370,  371,  372,  373,  374,  352,  375,  353,  376,  377,
      355,  357,  378,  356,  358,  359,  360,  379,  361,  381,
      362,  363,  364,  365,  368,  382,  369,  370,  371,  372,
      383,  373,  374,  375,  384,  376,  377,  385,  386,  378,
      388,  389,  434,  434,  379,  434,  381,  434,  434,  434,

      434,  434,  382,  434,  434,  434,  434,  383,  434,  434,
      434,  384,  434,  434,  385,  434,  386,  388,  389,   67,
       67,  101,  434,  101,  101,  101,  101,  101,  102,  102,
      102,  102,  102,  102,  109,  109,  235,  434,  235,    3,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,

      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434
    } ;

static const flex_int16_t yy_chk[1126] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    5,    6,    6,    9,
       10,   14,   17,   17,   10,   10,   10,   10,   10,   10,

       10,   10,   22,   22,   43,   43,   10,   47,  102,   14,
       47,  102,   23,  443,   26,   10,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   19,  442,   29,  440,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       23,   25,   26,   10,   27,   30,   28,  315,   27,  439,
       31,  432,   25,   27,   27,   25,   29,   27,   28,   32,
       33,   34,  109,   35,  315,   35,    9,   68,   37,   25,
      431,  430,   27,   30,   28,   27,   19,   31,   36,   25,
       27,   27,   25,   38,   27,   28,   41,   32,   33,   34,
       35,   38,   35,   39,   68,   36,   37,   40,   36,   40,

       70,   39,   73,  429,  103,  428,   36,  103,  427,  228,
      280,   38,  109,  426,   41,  228,  280,  228,  280,   38,
      425,   39,   36,  424,   40,   36,   40,   49,   70,   39,
       73,   49,   49,   49,   49,   49,   49,   49,   49,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   62,
       69,   76,  423,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,  422,   69,   71,   71,   49,   53,   79,
       53,  421,   53,   77,  420,  419,   80,   82,   69,   76,
       74,   53,   53,   53,   53,   53,   53,   53,   53,   53,

       53,   69,   71,   71,   72,   78,   79,   74,   74,   62,
       81,   77,   75,   80,   82,   83,   78,   72,   74,  418,
       72,   87,   84,  417,  416,   75,   81,   85,  415,   75,
       88,   89,   72,   78,   74,   74,  414,   89,   81,   90,
       75,   92,   83,   78,   72,   53,   53,   72,   87,   53,
       84,   53,   75,   81,   53,   85,   75,   88,   91,   89,
       93,   94,   97,   91,   89,   95,   96,   90,   92,   98,
      119,  122,   94,  105,  105,  105,  105,  105,  105,  105,
      105,  413,  412,  411,  410,  409,   91,   93,  408,   94,
       97,   91,   95,   96,  111,  407,   98,  119,  122,   94,

      406,  405,  404,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  112,  114,  114,  114,  114,  114,  114,
      114,  114,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  113,  120,  121,  403,  123,  120,  402,  124,
      124,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  117,  117,  117,  117,  117,  117,  117,  117,  117,
      117,  120,  121,  123,  125,  120,  124,  124,  126,  127,
      128,  129,  130,  401,  131,  132,  133,  400,  134,  135,
      136,  137,  138,  139,  140,  141,  142,  399,  143,  144,
      145,  146,  125,  147,  148,  126,  127,  117,  128,  129,

      130,  131,  151,  132,  133,  134,  135,  150,  136,  137,
      138,  139,  140,  141,  142,  143,  144,  145,  149,  146,
      150,  147,  148,  152,  154,  155,  149,  156,  157,  151,
      158,  159,  169,  160,  161,  150,  164,  164,  164,  164,
      164,  164,  164,  164,  180,  149,  182,  150,  183,  184,
      152,  154,  155,  149,  156,  398,  157,  158,  397,  159,
      160,  396,  161,  165,  165,  165,  165,  165,  165,  165,
      165,  180,  187,  182,  172,  395,  183,  184,  394,  393,
      392,  391,  169,  172,  172,  172,  172,  172,  172,  172,
      172,  172,  172,  173,  390,  387,  380,  366,  344,  169,

      187,  317,  173,  173,  173,  173,  173,  173,  173,  173,
      173,  173,  174,  186,  188,  313,  189,  279,  176,  278,
      276,  174,  174,  174,  174,  174,  174,  176,  176,  176,
      176,  176,  176,  176,  176,  177,  235,  233,  231,  194,
      186,  190,  188,  189,  177,  177,  177,  177,  177,  177,
      177,  177,  179,  191,  179,  192,  193,  179,  179,  179,
      179,  179,  179,  179,  179,  179,  179,  194,  190,  195,
      196,  226,  197,  198,  199,  200,  178,  201,  202,  207,
      191,  203,  192,  193,  204,  206,  208,  212,  213,  175,
      214,  215,  216,  218,  220,  225,  195,  221,  196,  197,

      198,  199,  222,  200,  201,  223,  202,  207,  203,  224,
      168,  204,  206,  208,  166,  212,  213,  214,  162,  215,
      216,  218,  220,  225,  221,  118,  110,  108,  107,  222,
      106,  104,  223,  100,   63,   54,  224,  227,  227,  227,
      227,  227,  227,  227,  227,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  238,  239,   51,  240,  242,
       48,  243,  244,  245,  246,  247,  248,   45,  249,  250,
      251,  252,  253,  227,  254,   42,  242,  255,   21,  256,
      258,  259,  264,  238,  239,  240,  261,  242,  243,  244,

      245,  246,  247,  263,  248,  249,  250,  265,  251,  252,
      253,  266,  254,  242,  267,  255,  256,  258,  268,  259,
      264,  269,  271,  261,  273,  275,   20,   18,   15,   12,
      263,   11,    8,    7,  281,  265,  283,    3,  284,  266,
      285,  286,  267,  287,  288,  289,  268,  290,  269,  271,
      291,  293,  273,  275,  277,  277,  277,  277,  277,  277,
      277,  277,  281,  295,  283,  284,  296,  285,  286,  297,
      287,  298,  288,  289,  299,  290,  300,  301,  291,  293,
      302,  303,    0,  304,  305,  306,  307,    0,  308,  312,
        0,  295,    0,  296,    0,    0,  297,  316,  321,  298,

      318,  299,  319,  300,  320,  301,  322,  328,  302,  303,
      304,  305,  306,  324,  307,  308,  312,  314,  314,  314,
      314,  314,  314,  314,  314,  316,  321,  318,  325,  319,
      327,  320,  329,  331,  322,  328,  330,  332,  335,  336,
      324,  337,  338,  340,  341,  343,    0,  346,  348,    0,
      349,  350,  351,  354,  355,  325,  356,  327,  358,  362,
      329,  331,  364,  330,  332,  335,  336,  365,  337,  369,
      338,  340,  341,  343,  346,  370,  348,  349,  350,  351,
      372,  354,  355,  356,  373,  358,  362,  374,  375,  364,
      382,  384,    0,    0,  365,    0,  369,    0,    0,    0,

        0,    0,  370,    0,    0,    0,    0,  372,    0,    0,
        0,  373,    0,    0,  374,    0,  375,  382,  384,  435,
      435,  436,    0,  436,  436,  436,  436,  436,  437,  437,
      437,  437,  437,  437,  438,  438,  441,    0,  441,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,

      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[95] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "eazy.l"
#line 4 "eazy.l"
#include <stdio.h>
#include "eazy.h"
#line 869 "lex.yy.c"
#line 870 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 8 "eazy.l"


#line 1090 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 435 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1040 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 10 "eazy.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 12 "eazy.l"
{printf("linea %d, palabra reservada: ABSTRACTO\n" , yylineno); return ABSTRACTO;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 13 "eazy.l"
{printf("linea %d, palabra reservada: CADA\n" , yylineno); return CADA;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 14 "eazy.l"
{printf("linea %d, palabra reservada: CADENA\n" , yylineno); return CADENA;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 15 "eazy.l"
{printf("linea %d, palabra reservada: CARACTER\n" , yylineno); return CARACTER;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 16 "eazy.l"
{printf("linea %d, palabra reservada: CLASE\n" , yylineno); return CLASE;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 17 "eazy.l"
{printf("linea %d, palabra reservada: COMO\n" , yylineno); return COMO;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 18 "eazy.l"
{printf("linea %d, palabra reservada: CONSTANTES\n" , yylineno); return CONSTANTES;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 19 "eazy.l"
{printf("linea %d, palabra reservada: CONSTRUCTOR\n" , yylineno); return CONSTRUCTOR;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 20 "eazy.l"
{printf("linea %d, palabra reservada: CONTINUAR\n" , yylineno); return CONTINUAR;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 21 "eazy.l"
{printf("linea %d, palabra reservada: DE\n" , yylineno); return DE;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 22 "eazy.l"
{printf("linea %d, palabra reservada: DEFECTO\n" , yylineno); return DEFECTO;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 23 "eazy.l"
{printf("linea %d, palabra reservada: DESTRUCTOR\n" , yylineno); return DESTRUCTOR;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 24 "eazy.l"
{printf("linea %d, palabra reservada: DEVOLVER\n" , yylineno); return DEVOLVER;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 25 "eazy.l"
{printf("linea %d, palabra reservada: EJECUTA\n" , yylineno); return EJECUTA;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 26 "eazy.l"
{printf("linea %d, palabra reservada: ENCAMBIO\n" , yylineno); return ENCAMBIO;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 27 "eazy.l"
{printf("linea %d, palabra reservada: ENTERO\n" , yylineno); return ENTERO;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 28 "eazy.l"
{printf("linea %d, palabra reservada: ENUMERACION\n" , yylineno); return ENUMERACION;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 29 "eazy.l"
{printf("linea %d, palabra reservada: EN\n" , yylineno); return EN;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 30 "eazy.l"
{printf("linea %d, palabra reservada: ES\n" , yylineno); return ES;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 31 "eazy.l"
{printf("linea %d, palabra reservada: ESCAPE\n" , yylineno); return ESCAPE;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 32 "eazy.l"
{printf("linea %d, palabra reservada: ESPECIFICO\n" , yylineno); return ESPECIFICO;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 33 "eazy.l"
{printf("linea %d, palabra reservada: ESTRUCTURA\n" , yylineno); return ESTRUCTURA;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 34 "eazy.l"
{printf("linea %d, palabra reservada: ETIQUETA\n" , yylineno); return ETIQUETA;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 35 "eazy.l"
{printf("linea %d, palabra reservada: EXCEPCION\n" , yylineno); return EXCEPCION;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 36 "eazy.l"
{printf("linea %d, palabra reservada: FICHERO\n" , yylineno); return FICHERO;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 37 "eazy.l"
{printf("linea %d, palabra reservada: FIN\n" , yylineno); return FIN;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 38 "eazy.l"
{printf("linea %d, palabra reservada: FINAL\n" , yylineno); return FINAL;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 39 "eazy.l"
{printf("linea %d, palabra reservada: FUNCION\n" , yylineno); return FUNCION;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 40 "eazy.l"
{printf("linea %d, palabra reservada: GENERICO\n" , yylineno); return GENERICO;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 41 "eazy.l"
{printf("linea %d, palabra reservada: HASH\n" , yylineno); return HASH;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 42 "eazy.l"
{printf("linea %d, palabra reservada: HACER\n" , yylineno); return HACER;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 43 "eazy.l"
{printf("linea %d, palabra reservada: IMPORTAR\n" , yylineno); return IMPORTAR;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 44 "eazy.l"
{printf("linea %d, palabra reservada: LANZA\n" , yylineno); return LANZA;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 45 "eazy.l"
{printf("linea %d, palabra reservada: MIENTRAS\n" , yylineno); return MIENTRAS;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 46 "eazy.l"
{printf("linea %d, palabra reservada: NADA\n" , yylineno); return NADA;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 47 "eazy.l"
{printf("linea %d, palabra reservada: OR\n" , yylineno); return OR;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 48 "eazy.l"
{printf("linea %d, palabra reservada: OTRA\n" , yylineno); return OTRA;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 49 "eazy.l"
{printf("linea %d, palabra reservada: PARA\n" , yylineno); return PARA;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 50 "eazy.l"
{printf("linea %d, palabra reservada: PRINCIPIO\n" , yylineno); return PRINCIPIO;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 51 "eazy.l"
{printf("linea %d, palabra reservada: PRIVADO\n" , yylineno); return PRIVADO;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 52 "eazy.l"
{printf("linea %d, palabra reservada: PROGRAMA\n" , yylineno); return PROGRAMA;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 53 "eazy.l"
{printf("linea %d, palabra reservada: PROTEGIDO\n" , yylineno); return PROTEGIDO;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 54 "eazy.l"
{printf("linea %d, palabra reservada: PUBLICO\n" , yylineno); return PUBLICO;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 55 "eazy.l"
{printf("linea %d, palabra reservada: REAL\n" , yylineno); return REAL;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 56 "eazy.l"
{printf("linea %d, palabra reservada: REF\n" , yylineno); return REF;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 57 "eazy.l"
{printf("linea %d, palabra reservada: SALTAR\n" , yylineno); return SALTAR;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 58 "eazy.l"
{printf("linea %d, palabra reservada: SI\n" , yylineno); return SI;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 59 "eazy.l"
{printf("linea %d, palabra reservada: SINO\n" , yylineno); return SINO;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 60 "eazy.l"
{printf("linea %d, palabra reservada: TAMANO\n" , yylineno); return TAMANO;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 61 "eazy.l"
{printf("linea %d, palabra reservada: TABLA\n" , yylineno); return TABLA;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 62 "eazy.l"
{printf("linea %d, palabra reservada: TIPOS\n" , yylineno); return TIPOS;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 63 "eazy.l"
{printf("linea %d, palabra reservada: ULTIMA\n" , yylineno); return ULTIMA;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 64 "eazy.l"
{printf("linea %d, palabra reservada: UNION\n" , yylineno); return UNION;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 65 "eazy.l"
{printf("linea %d, palabra reservada: VARIABLES\n" , yylineno); return VARIABLES;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 67 "eazy.l"
{printf("linea %d, operador: ASIG\n" , yylineno); return ASIG;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 68 "eazy.l"
{printf("linea %d, operador: AND_ASIG\n" , yylineno); return AND_ASIG;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 69 "eazy.l"
{printf("linea %d, operador: FLECHA_DCHA\n" , yylineno); return FLECHA_DCHA;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 70 "eazy.l"
{printf("linea %d, operador: FLECHA_IZDA\n" , yylineno); return FLECHA_IZDA;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 71 "eazy.l"
{printf("linea %d, operador: DIV_ASIG\n" , yylineno); return DIV_ASIG;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 72 "eazy.l"
{printf("linea %d, operador: EQ\n" , yylineno); return EQ;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 73 "eazy.l"
{printf("linea %d, operador: MOD_ASIG\n" , yylineno); return MOD_ASIG;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 74 "eazy.l"
{printf("linea %d, operador: MULT_ASIG\n" , yylineno); return MULT_ASIG;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 75 "eazy.l"
{printf("linea %d, operador: NEQ\n" , yylineno); return NEQ;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 76 "eazy.l"
{printf("linea %d, operador: POT_ASIG\n" , yylineno); return POT_ASIG;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 77 "eazy.l"
{printf("linea %d, operador: POTENCIA\n" , yylineno); return POTENCIA;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 78 "eazy.l"
{printf("linea %d, operador: RESTA_ASIG\n" , yylineno); return RESTA_ASIG;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 79 "eazy.l"
{printf("linea %d, operador: SUMA_ASIG\n" , yylineno); return SUMA_ASIG;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 80 "eazy.l"
{printf("linea %d, operador: XOR_ASIG\n" , yylineno); return XOR_ASIG;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 81 "eazy.l"
{printf("linea %d, operador: SUMA\n" , yylineno); return '+';}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 82 "eazy.l"
{printf("linea %d, operador: RESTA\n" , yylineno); return '-';}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 83 "eazy.l"
{printf("linea %d, operador: MULT\n" , yylineno); return '*';}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 84 "eazy.l"
{printf("linea %d, operador: DIV\n" , yylineno); return '/';}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 85 "eazy.l"
{printf("linea %d, operador: MOD\n" , yylineno); return '%';}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 87 "eazy.l"
{printf("linea %d, constante entera octal: %s\n", yylineno, yytext); return CTC_ENTERA;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 88 "eazy.l"
{printf("linea %d, constante entera hexadecimal: %s\n", yylineno, yytext); return CTC_ENTERA;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 89 "eazy.l"
{printf("linea %d, constante entera decimal: %s\n", yylineno, yytext); return CTC_ENTERA;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 91 "eazy.l"
{printf("linea %d, constante real octal: %s\n", yylineno, yytext); return CTC_REAL;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 92 "eazy.l"
{printf("linea %d, constante real hexadecimal: %s\n", yylineno, yytext); return CTC_REAL;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 93 "eazy.l"
{printf("linea %d, constante real decimal: %s\n", yylineno, yytext); return CTC_REAL;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 95 "eazy.l"
{printf("linea %d, constante real con exponente decimal: %s\n", yylineno, yytext); return CTC_REAL;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 96 "eazy.l"
{printf("linea %d, constante real con exponente octal: %s\n", yylineno, yytext); return CTC_REAL;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 97 "eazy.l"
{printf("linea %d, constante real con exponente hexadecimal: %s\n", yylineno, yytext); return CTC_REAL;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 99 "eazy.l"
{
    int value;
    if (sscanf(yytext, "\"\\%%%o\"", &value) == 1) { // Octal
        if (value > 127) {
            printf("Error: Valor octal fuera de rango en la línea %d: %s\n", yylineno, yytext);
        } else {
            printf("linea %d, constante de caracter (octal): %s\n", yylineno, yytext);
            return CTC_CARACTER;
        }
    } else if (sscanf(yytext, "\"\\%%h%x\"", &value) == 1 || sscanf(yytext, "\"\\%%H%x\"", &value) == 1) { // Hexadecimal
        if (value > 127) {
            printf("Error: Valor hexadecimal fuera de rango en la línea %d: %s\n", yylineno, yytext);
        } else {
            printf("linea %d, constante de caracter (hexadecimal): %s\n", yylineno, yytext);
            return CTC_CARACTER;
        }
    } else if (strlen(yytext) == 3) { 
        printf("linea %d, constante de caracter: %s\n", yylineno, yytext);
        return CTC_CARACTER;
    } else if (strcmp(yytext, "\"\\%%\"") == 0 || strcmp(yytext, "\"\\%n\"") == 0 || strcmp(yytext, "\"\\%r\"") == 0 || 
               strcmp(yytext, "\"\\%t\"") == 0 || strcmp(yytext, "\"\\%f\"") == 0 || strcmp(yytext, "\"\\%\"") == 0) { // Escapados
        printf("linea %d, constante de caracter escapado: %s\n", yylineno, yytext);
        return CTC_CARACTER;
    } else {
        printf("Error: Constante de caracter inválida en la línea %d: %s\n", yylineno, yytext);
    }
}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 127 "eazy.l"
{ printf("linea %d, constante de caracter: %s\n", yylineno, yytext); return CTC_CARACTER; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 128 "eazy.l"
{
    printf("linea %d, constante de caracter: %s\n", yylineno, yytext);
    return CTC_CARACTER;
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 132 "eazy.l"
{
    printf("linea %d, constante de caracter: %s\n", yylineno, yytext);
    return CTC_CARACTER;
}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 136 "eazy.l"
{
    printf("linea %d, constante de caracter: %s\n", yylineno, yytext);
    return CTC_CARACTER;
}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 141 "eazy.l"
{printf("linea %d, identificador: %s\n", yylineno, yytext); return IDENTIFICADOR;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 143 "eazy.l"
{ 
    printf("linea %d, delimitador: %s\n", yylineno, yytext); 
    return yytext[0]; 
}
	YY_BREAK
case 91:
/* rule 91 can match eol */
YY_RULE_SETUP
#line 148 "eazy.l"
;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 149 "eazy.l"
;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 151 "eazy.l"
{
    printf("linea %d, ERROR: %s\n", yylineno, yytext);
}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 155 "eazy.l"
ECHO;
	YY_BREAK
#line 1669 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 435 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 435 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 434);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 155 "eazy.l"


int yywrap() {
    return 1;
}

int main(int argc, char *argv[]) {
    if (argc < 2) {
        printf("Uso: ./eazy NombreArchivo\n");
        return 1;
    }
    yyin = fopen(argv[1], "r");
    if (!yyin) {
        perror("Error al abrir el archivo");
        return 1;
    }
    while (yylex());
    fclose(yyin);
    return 0;
}
