
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 124
#define YY_END_OF_BUFFER 125
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[464] =
    {   0,
        0,    0,    0,    0,    0,    0,  125,  121,    1,    1,
       96,  123,  123,   86,   72,   73,   80,   78,  121,   79,
       76,   81,   60,   74,   75,   90,  121,   91,  113,   88,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  116,
      117,  114,  120,  120,  118,   87,  119,   89,  120,    6,
        5,    6,    1,   95,    0,  122,    0,    0,   69,    2,
        0,    0,    3,   61,    0,    0,   97,  108,   83,  102,
      100,   63,  101,   85,  103,    0,   60,    0,   77,   99,
       84,   92,   94,   93,  109,  120,  120,  120,  120,  120,

       16,  120,   24,   25,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,   42,  120,  120,  120,  120,  120,
      120,   53,  120,  120,  120,  120,  120,  115,  120,  120,
      110,   98,    4,  122,    0,    0,    0,    2,    0,   64,
       62,    0,  105,  107,    0,  106,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,   32,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
       51,  120,  120,  120,  120,  120,  120,  120,  120,   82,
      120,    0,    0,    0,    0,    0,  120,    8,  120,  120,

      120,   12,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,   36,  120,  120,  120,   41,   43,   44,  120,  120,
      120,  120,  120,   50,  120,   54,  120,  120,  120,  120,
      120,  120,  104,  120,    0,    0,    0,    0,    0,    0,
       66,  120,  120,  120,   11,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
       33,  120,  120,   37,  120,   39,  120,  120,  120,  120,
      120,  120,  120,   55,  120,   56,  120,   58,  120,  120,
        0,    0,    0,    0,    0,    0,   66,    0,  120,    9,

      120,  120,  120,  120,  120,  120,  120,  120,  120,   22,
      120,   26,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,   52,  112,   57,  120,
      111,    0,    0,    0,    0,   67,    0,   65,    0,  120,
      120,  120,  120,  120,   17,  120,  120,   20,  120,  120,
      120,  120,  120,  120,   31,   34,  120,  120,  120,  120,
       46,  120,  120,   49,  120,    0,    0,   67,    0,    0,
       65,    0,  120,   10,  120,  120,  120,  120,   19,   21,
      120,  120,  120,   29,  120,   35,   38,   40,  120,   47,
      120,  120,    0,    0,    0,    0,    0,    0,    7,  120,

      120,   15,  120,  120,  120,  120,   30,   45,   48,   59,
        0,    0,    0,    0,    0,   66,   13,  120,   18,  120,
       27,   28,    0,    0,    0,    0,    0,    0,   68,   14,
       23,    0,    0,    0,   67,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   70,
        0,   71,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   20,   20,   20,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   41,   42,   43,   44,   45,   46,
       47,   48,   49,   50,   51,   52,   41,   53,   41,   54,
       55,    1,   56,   57,   58,    1,   59,   60,   61,   62,

       63,   64,   65,   66,   67,   68,   41,   69,   70,   71,
       72,   73,   74,   75,   76,   77,   78,   79,   41,   80,
       41,   81,   82,   83,   84,   85,    1,    1,   86,    1,
        1,    1,    1,    1,    1,    1,   86,    1,    1,    1,
       86,    1,    1,    1,   86,    1,   86,    1,    1,    1,
        1,    1,    1,   86,    1,   86,    1,    1,    1,    1,
       86,    1,    1,    1,    1,    1,    1,    1,   86,    1,
        1,    1,   86,    1,    1,    1,   86,    1,   86,    1,
        1,    1,    1,    1,    1,   86,    1,   86,    1,    1,
        1,    1,    1,    1,   86,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[87] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    1,
        1,    4,    3,    4,    1,    1,    5,    5,    5,    5,
        5,    5,    5,    1,    1,    1,    1,    1,    1,    1,
        5,    5,    5,    5,    5,    5,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    1,    1,    1,    6,    5,    5,
        5,    5,    5,    5,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    1,    1,    1,    1,    6
    } ;

static const flex_int16_t yy_base[474] =
    {   0,
        0,    0,    0,    0,   84,   85,  950, 1006,   87,   89,
      921,   88,  117,   88, 1006, 1006,   85,  920,   85,   70,
     1006,  919,  126,   86, 1006,   97,  918,  914, 1006,  912,
       67,    0,  109,   79,  127,  118,   93,  100,  109,  101,
      119,  131,  116,  151,  138,  166,  169,  169,  153, 1006,
     1006,  906,  148,  175, 1006,   82, 1006, 1006,    0, 1006,
     1006,  926,  114, 1006,  211, 1006,  216,  225, 1006,    0,
      868,  233, 1006,  242,    0,  853, 1006, 1006,  874, 1006,
     1006,  247, 1006,  866, 1006,  254,  277,  796, 1006, 1006,
      804, 1006, 1006, 1006, 1006,    0,  169,  244,  178,  237,

      252,  222,  272,  280,  244,  251,  276,  258,  271,  285,
      271,  277,  251,  290,    0,  279,  284,  300,  303,  307,
      309,  311,  326,  310,  310,  297,  314, 1006,  763,  333,
     1006, 1006, 1006,  368,  389,  374,  379,    0,  777,  396,
        0,  749, 1006, 1006,  712, 1006,  325,  346,  339,  342,
      354,  361,  365,  354,  361,  375,  388,  385,  380,  390,
      389,  381,  383,  390,  396,  404,  406,  405,  406,  404,
      399,  391,  402,  420,  423,  424,  432,  424,  416,  423,
        0,  425,  432,  436,  449,  441,  442,  442,  449,  757,
      459,  488,  769,  699,  722,  511,  447,    0,  453,  465,

      464,    0,  460,  468,  479,  467,  478,  485,  495,  491,
      506,  497,  511,  495,  497,  503,  515,  510,  514,  507,
      508,    0,  509,  527,  510,    0,    0,    0,  528,  531,
      516,  532,  529,    0,  540,    0,  543,  533,  531,  542,
      544,  561, 1006,  550,  592,  756,  702,  161,  609,  616,
      623,  572,  588,  555,    0,  617,  579,  574,  601,  601,
      604,  617,  610,  608,  622,  619,  626,  625,  628,  615,
        0,  621,  628,    0,  619,    0,  622,  632,  638,  642,
      637,  642,  630,    0,  639,    0,  660,    0,  662,  653,
      701,  712,  721,  708,    0,  214,  695,  651,  675,    0,

      674,  660,  667,  669,  676,  691,  691,  697,  690,    0,
      699,    0,  710,  673,  699,  714,  710,  715,  727,  730,
      731,  718,  720,  723,  728,  724,    0,    0,    0,  728,
        0,  766,  628,  785,  792,  799,  651,  599,  580,  723,
      732,  758,  790,  793,    0,  776,  779,    0,  783,  796,
      791,  781,  802,  791,    0,    0,  792,  790,  790,  795,
        0,  810,  808,    0,  808,  839,  599,  829,  550,  600,
      530,  557,  811,    0,  825,  817,  820,  828,    0,    0,
      835,  842,  829,    0,  834,    0,    0,    0,  834,    0,
      835,  832,  879,  598,  571,  587,  533,    0,    0,  833,

      841,    0,  841,  845,  846,  861,    0,    0,    0,    0,
      891,  582,  544,  503,  106,    0,    0,  850,    0,  855,
        0,    0,  905,  909,  470,    0,  496,  149,  227,    0,
        0,  916,  922,  462,    0,  489,  925,  928,  482,  482,
      938,  436,  420,  415,  331,  374,  354,  304,  239,  233,
      251,  197,  234,  228,  210,  159,  179,  222,  146, 1006,
      143, 1006, 1006,  980,  986,  988,  994,  145,  998,  136,
      124, 1000,  114
    } ;

static const flex_int16_t yy_def[474] =
    {   0,
      463,    1,    1,    1,  464,  464,  463,  463,  463,  463,
      463,  465,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  463,
      463,  463,  466,  466,  463,  463,  463,  463,  466,  463,
      463,  463,  463,  463,  465,  463,  465,  465,  463,  467,
      463,  463,  463,  463,  468,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  466,  466,  466,  466,  466,

      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  463,  466,  466,
      463,  463,  463,  465,  465,  465,  465,  467,  463,  463,
      468,  463,  463,  463,  463,  463,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  465,  463,  463,  463,  463,  466,  466,  466,  466,

      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  463,  466,  465,  463,  463,  469,  463,  463,
      463,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      465,  463,  463,  463,  470,  469,  463,  463,  466,  466,

      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  465,  463,  463,  463,  463,  463,  470,  463,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  465,  463,  463,  463,  463,
      470,  463,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  465,  463,  463,  463,  463,  471,  466,  466,

      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      465,  463,  463,  463,  472,  471,  466,  466,  466,  466,
      466,  466,  465,  465,  463,  473,  463,  472,  472,  466,
      466,  465,  465,  463,  473,  463,  465,  465,  463,  463,
      465,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,    0,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463
    } ;

static const flex_int16_t yy_nxt[1093] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,    8,   15,   16,
       17,   18,   19,   20,   21,   22,   23,   23,   23,   23,
       23,   23,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   32,
       32,   40,   41,   42,   43,   44,   32,   45,   46,   47,
       48,   49,   32,   32,   50,   51,   52,   32,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   32,   40,   53,
       42,   43,   44,   32,   45,   46,   54,   48,   49,   32,
       32,   55,   56,   57,   58,   59,   61,   61,   63,   63,
       63,   63,   66,   67,   77,   79,   83,   84,   97,   62,

       62,   82,   82,   82,   82,   82,   82,   82,  131,   89,
       91,   80,   90,  101,   78,   63,   63,  428,  435,  428,
       68,   69,   70,   92,   69,   71,   97,  109,  416,   72,
      110,  112,   73,   74,   74,   74,   74,   74,   86,   98,
      338,  101,   87,   87,   87,   87,   87,   87,   87,  141,
       99,  111,  462,  100,   75,  109,  107,  113,  110,  112,
      463,  114,  463,  115,  132,  116,  102,   98,  108,  294,
      103,   76,  120,  295,  461,  104,  105,   99,  111,  106,
      100,  117,   75,  127,  107,  113,  113,   69,   88,  114,
      115,   69,  116,   69,  102,  108,  121,  103,  118,  123,

      120,  119,  104,  105,  122,  123,  106,  124,  150,  117,
      125,  127,  126,  124,  113,   66,   67,  147,   65,  129,
      134,  135,  463,  136,  121,  118,  295,  123,  119,   66,
       67,  460,  122,  130,  459,  124,  150,  125,  463,  126,
      463,  124,  458,   68,  147,  457,  456,  455,   68,  140,
      140,  140,  140,  140,   72,  137,  156,   68,   74,   74,
       74,   74,   74,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,  148,  454,  151,
      152,  453,  163,  164,  156,  173,  136,  153,  452,   86,
      136,  149,  136,   87,   87,   87,   87,   87,   87,   87,

      154,  167,  451,  155,  157,  148,  151,  152,  165,   88,
      163,  164,  160,  173,  168,  153,  171,  169,  149,  166,
      172,  158,  159,  174,  450,  161,  175,  154,  167,  162,
      155,  176,  157,  170,  179,  188,  165,  180,  177,   88,
      160,  168,  181,  171,  178,  169,  166,  172,  158,  159,
      182,  174,  161,  175,  183,  186,  162,  184,  176,  187,
      170,  189,  179,  188,  184,  180,  177,  449,  185,  200,
      181,  178,   66,   67,  197,  185,  198,  182,   66,   67,
      199,  183,  186,   66,   67,  184,  187,  448,  189,  447,
      201,   65,  184,  134,  135,  185,  136,  200,  202,  205,

       68,  197,  191,  206,  198,  207,   68,  208,  199,  203,
      204,   68,  140,  140,  140,  140,  140,  201,  209,  210,
      212,   68,  211,  213,  216,  202,  192,  205,  214,  215,
      206,  446,  207,  217,  218,  208,  203,  204,  219,  220,
      221,  222,  445,  223,  224,  225,  209,  210,  212,  211,
      226,  213,  216,  227,  228,  214,  215,  233,  194,  136,
      231,  217,  218,  136,  234,  136,  219,  220,  221,  222,
      223,  224,  225,  232,  235,  229,  236,  237,  226,  238,
      240,  227,  228,  230,  233,  239,  241,  242,  231,  238,
      444,  234,   66,   67,  252,  443,  253,  254,  255,  442,

      232,  235,  229,  236,  237,  440,  257,  238,  240,  256,
      230,  258,  239,  241,  259,  242,  249,  244,  245,  260,
       68,  252,  250,  253,  250,  254,  255,  251,  251,  251,
      251,  251,  251,  251,  257,  261,  256,  262,  263,  258,
      264,  259,  265,  266,  439,  267,  260,  268,  269,  270,
      436,  271,  272,  434,  273,  274,  275,  276,  427,  277,
      278,  279,  261,  280,  262,  263,  281,  282,  264,  265,
      283,  266,  267,  284,  268,  269,  285,  270,  271,  286,
      272,  273,  274,  275,  287,  276,  277,  288,  278,  279,
      280,  289,  371,  285,  281,  282,   66,   67,  283,  426,

      425,  284,  299,  285,  301,  415,  286,  414,  413,  397,
      412,  287,  398,  396,  288,  395,  394,  372,  300,  289,
      290,  249,  304,  305,  291,  297,  297,  297,  297,  297,
      299,  301,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  300,  302,  309,  304,
      305,  306,  307,  308,  310,  311,  312,  313,  314,  315,
      316,  371,  317,  298,  303,  318,  319,  370,  320,  321,
      322,  323,  324,  325,  326,  302,  309,  327,  306,  307,
      308,  310,  311,  328,  312,  313,  314,  315,  316,  317,
      329,  303,  318,  330,  319,  320,  321,  328,  322,  323,

      324,  325,  326,  342,  327,   66,   67,  340,  341,  367,
      328,  297,  297,  297,  297,  297,  339,  343,  329,  344,
      345,  330,  352,  346,  331,  347,  334,  348,  349,  350,
      342,  137,  335,   68,  335,  340,  341,  336,  336,  336,
      336,  336,  336,  336,  343,  351,  344,  345,  353,  352,
      332,  346,  354,  347,  355,  348,  349,  350,  356,  357,
      358,  359,  337,  360,  361,  362,  363,  333,  364,  365,
       66,   67,  373,  351,  293,  353,  292,  248,  247,  374,
      354,  355,  246,  243,  196,  356,  195,  357,  358,  359,
      360,  361,  362,  193,  363,  364,  365,  334,   68,  373,

      366,  368,  368,  368,  368,  368,  374,  375,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  376,  377,  190,  378,  379,  380,  381,  382,
      146,  383,  384,  389,  375,  385,  386,  387,  388,  369,
      390,  391,  392,   66,   67,  368,  368,  368,  368,  368,
      376,  377,  378,  379,  380,  399,  381,  382,  383,  400,
      384,  389,  385,  386,  387,  388,  401,  402,  390,  391,
      392,   68,  403,  404,  405,  145,  406,  407,  408,  409,
      410,  417,  399,   66,   67,  418,  393,  400,  419,  420,
      421,  422,  144,  401,  402,   66,   67,  430,  431,  403,

      143,  404,  405,  406,  407,  408,  409,  410,  417,   66,
       67,   68,  418,   66,   67,  419,  420,  421,  142,  422,
       66,   67,  139,   68,  430,  431,   66,   67,  423,   66,
       67,  133,   66,   67,  128,  424,  411,   68,   95,  432,
       94,  433,   66,   67,   93,   85,   81,   64,   68,  463,
      463,  463,  137,  463,   68,  136,  463,   68,  441,  463,
       68,  463,  463,  463,  463,  463,  463,  463,  437,  463,
       68,  438,  463,  463,  463,  463,  463,  463,  463,  136,
       60,   60,   60,   60,   60,   60,   65,  463,   65,   65,
       65,   65,   96,   96,  138,  463,  138,  138,  138,  138,

      296,  463,  296,  429,  429,    7,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463

    } ;

static const flex_int16_t yy_chk[1093] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    5,    6,    9,    9,
       10,   10,   12,   12,   14,   17,   20,   20,   31,    5,

        6,   19,   19,   19,   19,   19,   19,   19,   56,   24,
       26,   17,   24,   34,   14,   63,   63,  415,  473,  415,
       12,   13,   13,   26,   13,   13,   31,   37,  471,   13,
       38,   40,   13,   13,   13,   13,   13,   13,   23,   33,
      470,   34,   23,   23,   23,   23,   23,   23,   23,  468,
       33,   39,  461,   33,   13,   37,   36,   41,   38,   40,
      428,   42,  428,   43,   56,   43,   35,   33,   36,  248,
       35,   13,   45,  248,  459,   35,   35,   33,   39,   35,
       33,   44,   13,   49,   36,   41,   53,   13,   23,   42,
       43,   13,   43,   13,   35,   36,   46,   35,   44,   47,

       45,   44,   35,   35,   46,   54,   35,   47,   99,   44,
       48,   49,   48,   54,   53,   65,   65,   97,   67,   53,
       67,   67,  296,   67,   46,   44,  296,   47,   44,   68,
       68,  458,   46,   54,  457,   47,   99,   48,  429,   48,
      429,   54,  456,   65,   97,  455,  454,  453,   67,   72,
       72,   72,   72,   72,   74,   68,  102,   68,   74,   74,
       74,   74,   74,   82,   82,   82,   82,   82,   82,   82,
       86,   86,   86,   86,   86,   86,   86,   98,  452,  100,
      100,  451,  105,  106,  102,  113,   67,  101,  450,   87,
       67,   98,   67,   87,   87,   87,   87,   87,   87,   87,

      101,  108,  449,  101,  103,   98,  100,  100,  107,   82,
      105,  106,  104,  113,  109,  101,  111,  110,   98,  107,
      112,  103,  103,  114,  448,  104,  116,  101,  108,  104,
      101,  117,  103,  110,  119,  126,  107,  120,  118,   87,
      104,  109,  120,  111,  118,  110,  107,  112,  103,  103,
      121,  114,  104,  116,  122,  124,  104,  123,  117,  125,
      110,  127,  119,  126,  130,  120,  118,  447,  123,  149,
      120,  118,  134,  134,  147,  130,  148,  121,  136,  136,
      148,  122,  124,  137,  137,  123,  125,  446,  127,  445,
      150,  135,  130,  135,  135,  123,  135,  149,  151,  153,

      134,  147,  130,  154,  148,  155,  136,  156,  148,  152,
      152,  137,  140,  140,  140,  140,  140,  150,  157,  158,
      160,  135,  159,  161,  164,  151,  137,  153,  162,  163,
      154,  444,  155,  165,  166,  156,  152,  152,  167,  168,
      169,  170,  443,  171,  172,  173,  157,  158,  160,  159,
      174,  161,  164,  175,  176,  162,  163,  179,  140,  135,
      178,  165,  166,  135,  180,  135,  167,  168,  169,  170,
      171,  172,  173,  178,  182,  177,  183,  184,  174,  185,
      187,  175,  176,  177,  179,  186,  188,  189,  178,  191,
      442,  180,  192,  192,  197,  440,  199,  200,  201,  439,

      178,  182,  177,  183,  184,  436,  204,  185,  187,  203,
      177,  205,  186,  188,  206,  189,  196,  191,  192,  207,
      192,  197,  196,  199,  196,  200,  201,  196,  196,  196,
      196,  196,  196,  196,  204,  208,  203,  209,  210,  205,
      211,  206,  212,  213,  434,  214,  207,  215,  216,  217,
      427,  218,  219,  425,  220,  221,  223,  224,  414,  225,
      229,  230,  208,  231,  209,  210,  232,  233,  211,  212,
      235,  213,  214,  237,  215,  216,  238,  217,  218,  239,
      219,  220,  221,  223,  240,  224,  225,  241,  229,  230,
      231,  242,  371,  244,  232,  233,  245,  245,  235,  413,

      412,  237,  252,  238,  254,  397,  239,  396,  395,  371,
      394,  240,  372,  370,  241,  369,  367,  339,  253,  242,
      244,  250,  257,  258,  245,  249,  249,  249,  249,  249,
      252,  254,  250,  250,  250,  250,  250,  250,  250,  251,
      251,  251,  251,  251,  251,  251,  253,  256,  262,  257,
      258,  259,  260,  261,  263,  264,  265,  266,  267,  268,
      269,  338,  270,  249,  256,  272,  273,  337,  275,  277,
      278,  279,  280,  281,  282,  256,  262,  283,  259,  260,
      261,  263,  264,  285,  265,  266,  267,  268,  269,  270,
      287,  256,  272,  289,  273,  275,  277,  290,  278,  279,

      280,  281,  282,  302,  283,  291,  291,  299,  301,  333,
      285,  297,  297,  297,  297,  297,  298,  303,  287,  304,
      305,  289,  314,  306,  290,  307,  293,  308,  309,  311,
      302,  291,  293,  291,  293,  299,  301,  293,  293,  293,
      293,  293,  293,  293,  303,  313,  304,  305,  315,  314,
      291,  306,  316,  307,  317,  308,  309,  311,  318,  319,
      320,  321,  294,  322,  323,  324,  325,  292,  326,  330,
      332,  332,  340,  313,  247,  315,  246,  195,  194,  341,
      316,  317,  193,  190,  145,  318,  142,  319,  320,  321,
      322,  323,  324,  139,  325,  326,  330,  335,  332,  340,

      332,  334,  334,  334,  334,  334,  341,  342,  335,  335,
      335,  335,  335,  335,  335,  336,  336,  336,  336,  336,
      336,  336,  343,  344,  129,  346,  347,  349,  350,  351,
       91,  352,  353,  360,  342,  354,  357,  358,  359,  334,
      362,  363,  365,  366,  366,  368,  368,  368,  368,  368,
      343,  344,  346,  347,  349,  373,  350,  351,  352,  375,
      353,  360,  354,  357,  358,  359,  376,  377,  362,  363,
      365,  366,  378,  381,  382,   88,  383,  385,  389,  391,
      392,  400,  373,  393,  393,  401,  366,  375,  403,  404,
      405,  406,   84,  376,  377,  411,  411,  418,  420,  378,

       79,  381,  382,  383,  385,  389,  391,  392,  400,  423,
      423,  393,  401,  424,  424,  403,  404,  405,   76,  406,
      432,  432,   71,  411,  418,  420,  433,  433,  411,  437,
      437,   62,  438,  438,   52,  411,  393,  423,   30,  423,
       28,  424,  441,  441,   27,   22,   18,   11,  432,    7,
        0,    0,  433,    0,  433,  437,    0,  437,  438,    0,
      438,    0,    0,    0,    0,    0,    0,    0,  432,    0,
      441,  433,    0,    0,    0,    0,    0,    0,    0,  441,
      464,  464,  464,  464,  464,  464,  465,    0,  465,  465,
      465,  465,  466,  466,  467,    0,  467,  467,  467,  467,

      469,    0,  469,  472,  472,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463

    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[125] =
    {   0,
1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "eazy.l"
#line 4 "eazy.l"
#include <stdio.h>
#include "eazy.h"
#line 874 "lex.yy.c"

#line 876 "lex.yy.c"

#define INITIAL 0
#define COMENTARIO 1
#define MULTILINE 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 43 "eazy.l"





#line 1101 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 464 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1006 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 48 "eazy.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 50 "eazy.l"
{ printf("linea %d, comentario : %s\n", yylineno, yytext); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 51 "eazy.l"
{ BEGIN(MULTILINE); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 52 "eazy.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 53 "eazy.l"
{ yylineno++; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 54 "eazy.l"
{ printf("linea %d, comentarioooooooooooooooooooo : %s\n", yylineno, yytext);  }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 57 "eazy.l"
{printf("linea %d, palabra reservada: ABSTRACTO\n" , yylineno); return ABSTRACTO;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 58 "eazy.l"
{printf("linea %d, palabra reservada: CADA\n" , yylineno); return CADA;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 59 "eazy.l"
{printf("linea %d, palabra reservada: CADENA\n" , yylineno); return CADENA;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 60 "eazy.l"
{printf("linea %d, palabra reservada: CARACTER\n" , yylineno); return CARACTER;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 61 "eazy.l"
{printf("linea %d, palabra reservada: CLASE\n" , yylineno); return CLASE;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 62 "eazy.l"
{printf("linea %d, palabra reservada: COMO\n" , yylineno); return COMO;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 63 "eazy.l"
{printf("linea %d, palabra reservada: CONSTANTES\n" , yylineno); return CONSTANTES;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 64 "eazy.l"
{printf("linea %d, palabra reservada: CONSTRUCTOR\n" , yylineno); return CONSTRUCTOR;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 65 "eazy.l"
{printf("linea %d, palabra reservada: CONTINUAR\n" , yylineno); return CONTINUAR;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 66 "eazy.l"
{printf("linea %d, palabra reservada: DE\n" , yylineno); return DE;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 67 "eazy.l"
{printf("linea %d, palabra reservada: DEFECTO\n" , yylineno); return DEFECTO;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 68 "eazy.l"
{printf("linea %d, palabra reservada: DESTRUCTOR\n" , yylineno); return DESTRUCTOR;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 69 "eazy.l"
{printf("linea %d, palabra reservada: DEVOLVER\n" , yylineno); return DEVOLVER;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 70 "eazy.l"
{printf("linea %d, palabra reservada: EJECUTA\n" , yylineno); return EJECUTA;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 71 "eazy.l"
{printf("linea %d, palabra reservada: ENCAMBIO\n" , yylineno); return ENCAMBIO;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 72 "eazy.l"
{printf("linea %d, palabra reservada: ENTERO\n" , yylineno); return ENTERO;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 73 "eazy.l"
{printf("linea %d, palabra reservada: ENUMERACION\n" , yylineno); return ENUMERACION;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 74 "eazy.l"
{printf("linea %d, palabra reservada: EN\n" , yylineno); return EN;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 75 "eazy.l"
{printf("linea %d, palabra reservada: ES\n" , yylineno); return ES;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 76 "eazy.l"
{printf("linea %d, palabra reservada: ESCAPE\n" , yylineno); return ESCAPE;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 77 "eazy.l"
{printf("linea %d, palabra reservada: ESPECIFICO\n" , yylineno); return ESPECIFICO;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 78 "eazy.l"
{printf("linea %d, palabra reservada: ESTRUCTURA\n" , yylineno); return ESTRUCTURA;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 79 "eazy.l"
{printf("linea %d, palabra reservada: ETIQUETA\n" , yylineno); return ETIQUETA;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 80 "eazy.l"
{printf("linea %d, palabra reservada: EXCEPCION\n" , yylineno); return EXCEPCION;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 81 "eazy.l"
{printf("linea %d, palabra reservada: FICHERO\n" , yylineno); return FICHERO;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 82 "eazy.l"
{printf("linea %d, palabra reservada: FIN\n" , yylineno); return FIN;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 83 "eazy.l"
{printf("linea %d, palabra reservada: FINAL\n" , yylineno); return FINAL;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 84 "eazy.l"
{printf("linea %d, palabra reservada: FUNCION\n" , yylineno); return FUNCION;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 85 "eazy.l"
{printf("linea %d, palabra reservada: GENERICO\n" , yylineno); return GENERICO;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 86 "eazy.l"
{printf("linea %d, palabra reservada: HASH\n" , yylineno); return HASH;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 87 "eazy.l"
{printf("linea %d, palabra reservada: HACER\n" , yylineno); return HACER;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 88 "eazy.l"
{printf("linea %d, palabra reservada: IMPORTAR\n" , yylineno); return IMPORTAR;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 89 "eazy.l"
{printf("linea %d, palabra reservada: LANZA\n" , yylineno); return LANZA;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 90 "eazy.l"
{printf("linea %d, palabra reservada: MIENTRAS\n" , yylineno); return MIENTRAS;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 91 "eazy.l"
{printf("linea %d, palabra reservada: NADA\n" , yylineno); return NADA;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 92 "eazy.l"
{printf("linea %d, palabra reservada: OR\n" , yylineno); return OR;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 93 "eazy.l"
{printf("linea %d, palabra reservada: OTRA\n" , yylineno); return OTRA;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 94 "eazy.l"
{printf("linea %d, palabra reservada: PARA\n" , yylineno); return PARA;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 95 "eazy.l"
{printf("linea %d, palabra reservada: PRINCIPIO\n" , yylineno); return PRINCIPIO;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 96 "eazy.l"
{printf("linea %d, palabra reservada: PRIVADO\n" , yylineno); return PRIVADO;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 97 "eazy.l"
{printf("linea %d, palabra reservada: PROGRAMA\n" , yylineno); return PROGRAMA;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 98 "eazy.l"
{printf("linea %d, palabra reservada: PROTEGIDO\n" , yylineno); return PROTEGIDO;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 99 "eazy.l"
{printf("linea %d, palabra reservada: PUBLICO\n" , yylineno); return PUBLICO;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 100 "eazy.l"
{printf("linea %d, palabra reservada: REAL\n" , yylineno); return REAL;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 101 "eazy.l"
{printf("linea %d, palabra reservada: REF\n" , yylineno); return REF;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 102 "eazy.l"
{printf("linea %d, palabra reservada: SALTAR\n" , yylineno); return SALTAR;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 103 "eazy.l"
{printf("linea %d, palabra reservada: SI\n" , yylineno); return SI;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 104 "eazy.l"
{printf("linea %d, palabra reservada: SINO\n" , yylineno); return SINO;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 105 "eazy.l"
{printf("linea %d, palabra reservada: TABLA\n" , yylineno); return TABLA;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 106 "eazy.l"
{printf("linea %d, palabra reservada: TIPOS\n" , yylineno); return TIPOS;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 107 "eazy.l"
{printf("linea %d, palabra reservada: ULTIMA\n" , yylineno); return ULTIMA;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 108 "eazy.l"
{printf("linea %d, palabra reservada: UNION\n" , yylineno); return UNION;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 109 "eazy.l"
{printf("linea %d, palabra reservada: VARIABLES\n" , yylineno); return VARIABLES;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 112 "eazy.l"
{printf("linea %d, constante entera: %s\n" , yylineno, yytext); return CTC_ENTERA;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 113 "eazy.l"
{printf("linea %d, constante entera: %s\n" , yylineno, yytext); return CTC_ENTERA;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 114 "eazy.l"
{printf("linea %d, constante entera: %s\n", yylineno, yytext); return CTC_ENTERA;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 115 "eazy.l"
{printf("linea %d, constante real: %s\n" , yylineno, yytext); return CTC_REAL;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 116 "eazy.l"
{printf("linea %d, constante real: %s\n" , yylineno, yytext); return CTC_REAL;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 117 "eazy.l"
{printf("linea %d, constante real: %s\n" , yylineno, yytext); return CTC_REAL;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 118 "eazy.l"
{printf("linea %d, constante real: %s\n" , yylineno, yytext); return CTC_REAL;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 119 "eazy.l"
{printf("linea %d, constante real: %s\n" , yylineno, yytext); return CTC_REAL;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 120 "eazy.l"
{printf("linea %d, constante real: %s\n" , yylineno, yytext); return CTC_REAL;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 121 "eazy.l"
{printf("linea %d, caracter escapado: %s\n" , yylineno, yytext); return CARACTER;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 122 "eazy.l"
{printf("linea %d, caracter octal: %s\n" , yylineno, yytext); return CARACTER;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 123 "eazy.l"
{printf("linea %d, caracter hexadecimal: %s\n" , yylineno, yytext); return CARACTER;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 126 "eazy.l"
{printf("linea %d, delimitador: %s \n", yylineno, yytext); return (int)yytext[0];}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 127 "eazy.l"
{printf("linea %d, delimitador: %s \n", yylineno, yytext); return (int)yytext[0];}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 128 "eazy.l"
{printf("linea %d, delimitador: %s \n", yylineno, yytext); return (int)yytext[0];}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 129 "eazy.l"
{printf("linea %d, delimitador: %s \n", yylineno, yytext); return (int)yytext[0];}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 130 "eazy.l"
{printf("linea %d, delimitador: %s \n", yylineno, yytext); return (int)yytext[0];}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 131 "eazy.l"
{printf("linea %d, delimitador: %s \n", yylineno, yytext); return PTOS;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 134 "eazy.l"
{printf("linea %d, operador aritmetico: %s \n", yylineno, yytext); return (int)yytext[0];}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 135 "eazy.l"
{printf("linea %d, operador aritmetico: %s \n", yylineno, yytext); return (int)yytext[0];}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 136 "eazy.l"
{printf("linea %d, operador aritmetico: %s \n", yylineno, yytext); return (int)yytext[0];}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 137 "eazy.l"
{printf("linea %d, operador aritmetico: %s \n", yylineno, yytext); return (int)yytext[0];}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 138 "eazy.l"
{printf("linea %d, operador aritmetico: %s \n", yylineno, yytext); return MOD;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 139 "eazy.l"
{printf("linea %d, operador aritmetico: %s \n", yylineno, yytext); return POTENCIA;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 141 "eazy.l"
{printf("linea %d, operador de bits: %s \n", yylineno, yytext); return FLECHA_IZDA;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 142 "eazy.l"
{printf("linea %d, operador de bits: %s \n", yylineno, yytext); return FLECHA_DCHA;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 143 "eazy.l"
{printf("linea %d, operador de bits: %s \n", yylineno, yytext); return (int)yytext[0];}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 144 "eazy.l"
{printf("linea %d, operador de bits: %s \n", yylineno, yytext); return (int)yytext[0];}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 145 "eazy.l"
{printf("linea %d, operador de bits: %s \n", yylineno, yytext); return (int)yytext[0];}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 146 "eazy.l"
{printf("linea %d, operador de bits: %s \n", yylineno, yytext); return (int)yytext[0];}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 148 "eazy.l"
{printf("linea %d, operador relacional: %s \n", yylineno, yytext); return (int)yytext[0];}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 149 "eazy.l"
{printf("linea %d, operador relacional: %s \n", yylineno, yytext); return (int)yytext[0];}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 150 "eazy.l"
{printf("linea %d, operador relacional: %s \n", yylineno, yytext); return LE;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 151 "eazy.l"
{printf("linea %d, operador relacional: %s \n", yylineno, yytext); return GE;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 152 "eazy.l"
{printf("linea %d, operador relacional: %s \n", yylineno, yytext); return EQ;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 153 "eazy.l"
{printf("linea %d, operador relacional: %s \n", yylineno, yytext); return NEQ;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 155 "eazy.l"
{printf("linea %d, operador logico: %s \n", yylineno, yytext); return (int)yytext[0];}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 156 "eazy.l"
{printf("linea %d, operador logico: %s \n", yylineno, yytext); return AND;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 157 "eazy.l"
{printf("linea %d, operador logico: %s \n", yylineno, yytext); return OR;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 159 "eazy.l"
{printf("linea %d, operador de asignacion: %s \n", yylineno, yytext); return ASIG;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 160 "eazy.l"
{printf("linea %d, operador de asignacion: %s \n", yylineno, yytext); return SUMA_ASIG;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 161 "eazy.l"
{printf("linea %d, operador de asignacion: %s \n", yylineno, yytext); return RESTA_ASIG;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 162 "eazy.l"
{printf("linea %d, operador de asignacion: %s \n", yylineno, yytext); return MULT_ASIG;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 163 "eazy.l"
{printf("linea %d, operador de asignacion: %s \n", yylineno, yytext); return DIV_ASIG;}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 164 "eazy.l"
{printf("linea %d, operador de asignacion: %s \n", yylineno, yytext); return MOD_ASIG;}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 165 "eazy.l"
{printf("linea %d, operador de asignacion: %s \n", yylineno, yytext); return POT_ASIG;}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 166 "eazy.l"
{printf("linea %d, operador de asignacion: %s \n", yylineno, yytext); return FI_ASIG;}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 167 "eazy.l"
{printf("linea %d, operador de asignacion: %s \n", yylineno, yytext); return FD_ASIG;}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 168 "eazy.l"
{printf("linea %d, operador de asignacion: %s \n", yylineno, yytext); return AND_ASIG;}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 169 "eazy.l"
{printf("linea %d, operador de asignacion: %s \n", yylineno, yytext); return XOR_ASIG;}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 170 "eazy.l"
{printf("linea %d, operador de asignacion: %s \n", yylineno, yytext); return OR_ASIG;}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 172 "eazy.l"
{printf("linea %d, operador de acceso a memoria: %s \n", yylineno, yytext); return TAMANO;}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 173 "eazy.l"
{printf("linea %d, Identificador: TAMANO\n" , yylineno); return TAMANO;}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 174 "eazy.l"
{printf("linea %d, operador de acceso a memoria: %s \n", yylineno, yytext); return (int)yytext[0];}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 175 "eazy.l"
{printf("linea %d, operador de acceso a memoria: %s \n", yylineno, yytext); return (int)yytext[0];}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 176 "eazy.l"
{printf("linea %d, operador de acceso a memoria: %s \n", yylineno, yytext); return INDIRECCION;}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 177 "eazy.l"
{printf("linea %d, operador de acceso a memoria: %s \n", yylineno, yytext); return (int)yytext[0];}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 178 "eazy.l"
{printf("linea %d, operador de acceso a memoria: %s \n", yylineno, yytext); return (int)yytext[0];}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 179 "eazy.l"
{printf("linea %d, operador de acceso a memoria: %s \n", yylineno, yytext); return (int)yytext[0];}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 180 "eazy.l"
{printf("linea %d, operador de acceso a memoria: %s \n", yylineno, yytext); return (int)yytext[0];}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 183 "eazy.l"
{printf("linea %d, identificador: %s\n", yylineno, yytext); return IDENTIFICADOR;}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 184 "eazy.l"
{printf("linea %d, caracter: %s\n" , yylineno, yytext); return CARACTER;}
	YY_BREAK
case 122:
/* rule 122 can match eol */
YY_RULE_SETUP
#line 188 "eazy.l"
{ printf("linea %d, cadena: %s\n", yylineno, yytext); return CADENA; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 190 "eazy.l"
{ fprintf(stdout, "ERROR en línea %d: carácter inesperado '%s'\n", yylineno, yytext); }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 191 "eazy.l"
ECHO;
	YY_BREAK
#line 1791 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMENTARIO):
case YY_STATE_EOF(MULTILINE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 464 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 464 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 463);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 191 "eazy.l"




int yywrap() {
    return 1;
}

int main(int argc, char *argv[]) {
    if (argc < 2) {
        printf("Uso: ./eazy NombreArchivo\n");
        return 1;
    }
    yyin = fopen(argv[1], "r");
    if (!yyin) {
        perror("Error al abrir el archivo");
        return 1;
    }
    while (yylex());
    fclose(yyin);
    return 0;
}

